truth:
  name: PREPBUFR
  type: point
  url: https://noaa-reanalyses-pds.s3.amazonaws.com/observations/reanalysis/conv/prepbufr/{{ yyyymmdd[:4] }}/{{ yyyymmdd[4:6] }}/prepbufr/gdas.{{ yyyymmdd }}.t{{ hh }}z.prepbufr.nr
cycles:
  start: 2023-01-01T00:00:00
  step: 6
  stop: 2024-12-31T18:00:00
forecast:
  coords:
    latitude: latitude
    level: level
    longitude: longitude
    time:
      inittime: forecast_reference_time
      validtime: time
  name: Global-EAGLE-Anemoi
  path: /pscratch/sd/t/timothys/anemoi-house/gfs/0.25-degree/latlon/steps030k-nc1024-2x8encoders/inference-validation/global.{{ yyyymmdd[:4] }}-{{ yyyymmdd[4:6] }}-{{ yyyymmdd[6:8] }}T{{ hh }}.240h.nc
  projection:
    proj: latlon
leadtimes:
  start: 0
  step: 6
  stop: 48
meta:
  grids: "{{ meta.workdir }}/grids"
  workdir: /pscratch/sd/t/timothys/nested-eagle/observations/g004
paths:
  grids:
    forecast: "{{ meta.grids }}/forecast"
  obs: "{{ meta.workdir }}/obs"
  run: "{{ meta.workdir }}/run"
regrid:
  method: BILIN
  to: G004
variables:
  t2m:
    level_type: heightAboveGround
    levels: [2]
    name: 2t
  gh:
    level_type: isobaricInhPa
    levels: [500]
    name: gh
  sp:
    level_type: surface
    name: sp
  t:
    level_type: isobaricInhPa
    levels: [850]
    name: t
  u:
    level_type: isobaricInhPa
    levels: [250]
    name: u
  u10:
    level_type: heightAboveGround
    levels: [10]
    name: u_10m
  v:
    level_type: isobaricInhPa
    levels: [250]
    name: v
  v10:
    level_type: heightAboveGround
    levels: [10]
    name: v_10m
