# if you are just running 1 initialization, make start==end
start_date: "2023-03-01T00:00:00"
end_date: "2023-03-01T00:00:00"
freq: "6h"

# index at which the nested ds goes from LAM->global
lam_index: 75749

# path to raw inference files you want to post process
raw_inference_files_base_path: "/pscratch/sd/m/mlpope/gfs_hrrr/nc"

# this next section helps us to make a LCC grid structured.
# if not using LCC over CONUS, set to false and ignore lat/lon length.
lcc_info:
  lcc_flag: True
  lat_length: 211
  lon_length: 359

# information about global portion of your grid.
global_info:
  res: 1
  lat_min: 20.5
  lon_min: 225.5
  lat_max: 52.5
  lon_max: 299.5

# this next portion lists all variable info out so the script knows what variables to process.
# can be helpful if you don't care about all variables or levels.
# it will only process and save out what you list below.
level_variables:
  - q
  - gh
  - t
  - u
  - v
  - w

levels:
  - 100
  - 150
  - 200
  - 250
  - 300
  - 400
  - 500
  - 600
  - 700
  - 850
  - 925
  - 1000

vars_of_interest:
  - gh_100
  - gh_150
  - gh_200
  - gh_250
  - gh_300
  - gh_400
  - gh_500
  - gh_600
  - gh_700
  - gh_850
  - gh_925
  - gh_1000
  - q_100
  - q_150
  - q_200
  - q_250
  - q_300
  - q_400
  - q_500
  - q_600
  - q_700
  - q_850
  - q_925
  - q_1000
  - sh2
  - sp
  - t_100
  - t_150
  - t_200
  - t_250
  - t_300
  - t_400
  - t_500
  - t_600
  - t_700
  - t_850
  - t_925
  - t_1000
  - t2m
  - u_100
  - u_150
  - u_200
  - u_250
  - u_300
  - u_400
  - u_500
  - u_600
  - u_700
  - u_850
  - u_925
  - u_1000
  - u10
  - v_100
  - v_150
  - v_200
  - v_250
  - v_300
  - v_400
  - v_500
  - v_600
  - v_700
  - v_850
  - v_925
  - v_1000
  - v10
  - w_100
  - w_150
  - w_200
  - w_250
  - w_300
  - w_400
  - w_500
  - w_600
  - w_700
  - w_850
  - w_925
  - w_1000
  - u80
  - v80
  - accum_tp
